name: Hello World!

on:
  push:
    branches:
      - main
  pull_request:    
    branches: [main]
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  date_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Now it is
        run: |
          date
  dir_content_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Directory content
        run: |
          ls -l
